#!/usr/bin/env bash
# displays the contents of the current directory in list format.
#   only displays the part of the name after the first dash. 

list=$(ls)
for a in $list; do
  echo "$a" | cut -d '-' -f2
done
